project_id = "uaiymunelgvvnznkxeik"

[functions.fetch-events]
verify_jwt = false

[functions.fetch-gallery]
verify_jwt = false

[functions.fetch-resources]
verify_jwt = false

[functions.fetch-substacks]
verify_jwt = false