// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.28.0";

// src/lib/mcp/tools/list-upcoming-events.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find(
          (v) => typeof v === "string" && v.trim().startsWith("sb_publishable_")
        )?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error(
    "SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required"
  );
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function toolError(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}
function toolJson(text, structured) {
  return {
    content: [{ type: "text", text }],
    structuredContent: structured
  };
}

// src/lib/mcp/tools/list-upcoming-events.ts
var list_upcoming_events_default = defineTool({
  name: "list_upcoming_events",
  title: "List upcoming Fempower events",
  description: "List published, upcoming Fempower events in the UAE with date, location, price and registration link.",
  inputSchema: {
    limit: z.number().int().min(1).max(25).optional().describe("How many events to return. Defaults to 10.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return toolError("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("events").select(
      "slug,title,description,location,starts_at,ends_at,price_cents,currency,capacity"
    ).eq("status", "published").gte("starts_at", (/* @__PURE__ */ new Date()).toISOString()).order("starts_at", { ascending: true }).limit(limit ?? 10);
    if (error) return toolError(error.message);
    const events = (data ?? []).map((e) => ({
      ...e,
      url: `https://fempowerae.com/events/${e.slug}`,
      price: e.price_cents === 0 ? "Free" : `${e.currency} ${(e.price_cents / 100).toFixed(2)}`
    }));
    const text = events.length ? events.map(
      (e) => `${e.title} \u2014 ${new Date(e.starts_at).toUTCString()} \u2014 ${e.location ?? "UAE"} \u2014 ${e.price} \u2014 ${e.url}`
    ).join("\n") : "No upcoming events are published right now.";
    return toolJson(text, { events });
  }
});

// src/lib/mcp/tools/get-my-registrations.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_my_registrations_default = defineTool2({
  name: "get_my_registrations",
  title: "Get my event registrations",
  description: "List the signed-in member's Fempower event registrations, including ticket code, status and event date.",
  inputSchema: {
    upcoming_only: z2.boolean().optional().describe("Only return registrations for events that have not happened yet. Defaults to true.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ upcoming_only }, ctx) => {
    if (!ctx.isAuthenticated()) return toolError("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("registrations").select(
      "status,ticket_code,quantity,checked_in_at,created_at,events(slug,title,starts_at,location)"
    ).eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(50);
    if (error) return toolError(error.message);
    const now = Date.now();
    const rows = (data ?? []).filter((r) => {
      if (upcoming_only === false) return true;
      const ev = r.events;
      return ev?.starts_at ? new Date(ev.starts_at).getTime() >= now : true;
    });
    const text = rows.length ? rows.map((r) => {
      const ev = r.events;
      return `${ev?.title ?? "Event"} \u2014 ${ev?.starts_at ? new Date(ev.starts_at).toUTCString() : "date TBC"} \u2014 ${r.status} \u2014 ticket ${r.ticket_code} (x${r.quantity})`;
    }).join("\n") : "No registrations found.";
    return toolJson(text, { registrations: rows });
  }
});

// src/lib/mcp/tools/search-members.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z3 } from "npm:zod@^3.25.76";
var search_members_default = defineTool3({
  name: "search_members",
  title: "Search the member directory",
  description: "Search approved Fempower members by name, role, company, city, industry, expertise or interests. Returns only what the member chose to publish.",
  inputSchema: {
    query: z3.string().trim().min(2).describe("Free-text search, e.g. 'fintech Dubai' or 'coach'."),
    limit: z3.number().int().min(1).max(25).optional().describe("Max results. Defaults to 10.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return toolError("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const term = query.replace(/[,()*]/g, " ").trim();
    if (!term) return toolError("Please provide a searchable term.");
    const { data, error } = await supabase.from("member_profiles").select("name,role,company,city,industry,expertise_tags,interests,looking_for,bio,linkedin_url").eq("status", "approved").or(
      [
        `name.ilike.%${term}%`,
        `role.ilike.%${term}%`,
        `company.ilike.%${term}%`,
        `city.ilike.%${term}%`,
        `industry.ilike.%${term}%`,
        `bio.ilike.%${term}%`
      ].join(",")
    ).limit(limit ?? 10);
    if (error) return toolError(error.message);
    const members = data ?? [];
    const text = members.length ? members.map(
      (m) => `${m.name}${m.role ? ` \u2014 ${m.role}` : ""}${m.company ? ` at ${m.company}` : ""}${m.city ? ` (${m.city})` : ""}`
    ).join("\n") : `No approved members matched "${term}".`;
    return toolJson(text, { members });
  }
});

// src/lib/mcp/tools/list-meetups.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z4 } from "npm:zod@^3.25.76";
var list_meetups_default = defineTool4({
  name: "list_meetups",
  title: "List member meetups",
  description: "List published member-hosted meetups across the UAE. Host identity is masked according to each host's chosen visibility.",
  inputSchema: {
    emirate: z4.string().trim().optional().describe("Filter to one emirate, e.g. 'Dubai' or 'Abu Dhabi'."),
    limit: z4.number().int().min(1).max(25).optional().describe("Max results. Defaults to 10.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ emirate, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return toolError("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.rpc("get_meetups_public");
    if (error) return toolError(error.message);
    const now = Date.now();
    const meetups = (data ?? []).filter((m) => {
      if (new Date(m.starts_at).getTime() < now) return false;
      if (!emirate) return true;
      return (m.emirate ?? "").toLowerCase() === emirate.toLowerCase();
    }).sort(
      (a, b) => new Date(a.starts_at).getTime() - new Date(b.starts_at).getTime()
    ).slice(0, limit ?? 10);
    const text = meetups.length ? meetups.map(
      (m) => `${m.title} \u2014 ${new Date(m.starts_at).toUTCString()} \u2014 ${m.place}${m.emirate ? `, ${m.emirate}` : ""} (id: ${m.id})`
    ).join("\n") : "No upcoming meetups match that filter.";
    return toolJson(text, { meetups });
  }
});

// src/lib/mcp/tools/rsvp-to-meetup.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z5 } from "npm:zod@^3.25.76";
var rsvp_to_meetup_default = defineTool5({
  name: "rsvp_to_meetup",
  title: "RSVP to a meetup",
  description: "RSVP the signed-in member to a published member meetup. Use list_meetups first to get the meetup id.",
  inputSchema: {
    meetup_id: z5.string().uuid().describe("The meetup id returned by list_meetups.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ meetup_id }, ctx) => {
    if (!ctx.isAuthenticated()) return toolError("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("meetup_rsvps").upsert(
      { meetup_id, user_id: ctx.getUserId() },
      { onConflict: "meetup_id,user_id", ignoreDuplicates: true }
    ).select();
    if (error) return toolError(error.message);
    return toolJson("RSVP confirmed. See it at https://fempowerae.com/meetups", {
      rsvp: data?.[0] ?? { meetup_id, already_rsvped: true }
    });
  }
});

// src/lib/mcp/tools/get-my-checklists.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z6 } from "npm:zod@^3.25.76";
var get_my_checklists_default = defineTool6({
  name: "get_my_checklists",
  title: "Get my saved Zara checklist results",
  description: "Return the signed-in member's saved coaching checklist summaries (Invisible Labour Audit, The Ask, Am I Actually Fine?, Relocation Load).",
  inputSchema: {
    limit: z6.number().int().min(1).max(20).optional().describe("Max summaries. Defaults to 5.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return toolError("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("coach_checklist_results").select("checklist_key,checklist_label,summary,created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 5);
    if (error) return toolError(error.message);
    const results = data ?? [];
    const text = results.length ? results.map(
      (r) => `${r.checklist_label} (${new Date(r.created_at).toDateString()})
${r.summary}`
    ).join("\n\n") : "No saved checklist results. Run one with Zara at https://fempowerae.com/ai-coach-for-women-uae";
    return toolJson(text, { results });
  }
});

// src/lib/mcp/index.ts
var projectRef = "uaiymunelgvvnznkxeik";
var mcp_default = defineMcp({
  name: "fempower-landing",
  title: "FEmpower Landing",
  version: "0.1.0",
  instructions: "Tools for Fempower, a women's community in the UAE. Callers act as the signed-in member: browse published events and member-hosted meetups, check their own registrations and saved Zara coaching checklists, search the approved member directory, and RSVP to a meetup. Member data is protected by row-level security, so results are limited to what this member may see.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_upcoming_events_default,
    list_meetups_default,
    rsvp_to_meetup_default,
    get_my_registrations_default,
    search_members_default,
    get_my_checklists_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.28.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
